language: node_js
node_js:
  - "6"
env:
  - URL_DEV: mlshv-burberry-fake-shop-for-study-dev
  - URL_PROD: mlshv-burberry-fake-shop-for-study
script:
  - yarn run test
after_success:
  - yarn run build
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      now alias $(now build -t=$NOW_SH_TOKEN --public) $URL_PROD -t=$NOW_SH_TOKEN
    fi
  - if [ "$TRAVIS_BRANCH" = "develop" ]; then
      now alias $(now build -t=$NOW_SH_TOKEN --public) $URL_DEV -t=$NOW_SH_TOKEN
    fi
cache:
  yarn: true
  directories:
    - node_modules
